apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: myapp-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: myapp-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: velero-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-reader-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: myapp-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io